version: "3.8"

services:
  jupyter:
    depends_on:
      - postgres
    build:
      dockerfile: jupyter/Dockerfile
      context: .
    ports:
      - 8888:8888
    volumes:
      - type: bind
        source: ./jupyter/notebooks
        target: /home/jovyan/
      - type: bind
        source: ./data
        target: /home/jovyan/data
      - type: bind
        source: ./src
        target: /home/jovyan/src
    env_file:
      - .env
      - ./jupyter/.env
    environment:
      - JUPYTER_ENABLE_LAB=yes

  format-python:
    image: python:3.8-slim
    volumes:
      - type: bind
        source: ./
        target: /repo
    working_dir: /repo
    command: sh scripts/format.sh

  pipeline:
    depends_on:
      - postgres
    build:
      dockerfile: pipeline/Dockerfile
      context: .
    env_file: .env
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./pipeline
        target: /pipeline
      - type: bind
        source: ./src
        target: /pipeline/src
    command: python /pipeline/main.py

  postgres:
    image: postgres
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ./data/postgres
        target: /var/lib/postgresql/data/

  api:
    depends_on:
      - postgres
    build:
      dockerfile: api/Dockerfile
      context: .
    env_file: .env
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./src
        target: /app/src
      - type: bind
        source: ./data
        target: /data

  train:
    build:
      dockerfile: train/Dockerfile
      context: .
    env_file: .env
    volumes:
      - type: bind
        source: ./src
        target: /src
      - type: bind
        source: ./data
        target: /data
    command: python main.py

  get-random-entry:
    build:
      dockerfile: train/Dockerfile
      context: .
    env_file: .env
    volumes:
      - type: bind
        source: ./src
        target: /scripts/src
      - type: bind
        source: ./scripts
        target: /scripts
      - type: bind
        source: ./data
        target: /data
    command: python /scripts/get_random_entry.py
